# generated by datamodel-codegen:
#   filename:  controller-mode.schema.json

from __future__ import annotations

from enum import Enum
from typing import Literal

from pydantic import BaseModel


class Mode(Enum):
    rule_based = 'rule_based'
    rl = 'rl'


class Payload(BaseModel):
    mode: Mode


class Model(BaseModel):
    type: Literal['controller_mode']
    ts: float
    payload: Payload
