# generated by datamodel-codegen:
#   filename:  kpi-update.schema.json

from __future__ import annotations

from enum import Enum
from typing import Literal

from pydantic import BaseModel


class CurrentMode(Enum):
    rule_based = 'rule_based'
    rl = 'rl'


class Payload(BaseModel):
    avgVehicleWaitS: float
    throughput: float
    avgPedWaitS: float
    jaywalkEvents: int
    currentMode: CurrentMode


class Model(BaseModel):
    type: Literal['kpi_update']
    ts: float
    payload: Payload
