# generated by datamodel-codegen:
#   filename:  room-events.schema.json

from __future__ import annotations

from enum import Enum
from typing import Literal

from pydantic import BaseModel, Field


class Payload(BaseModel):
    kind: Literal['user_join']
    clientId: str
    carId: str


class Payload1(BaseModel):
    kind: Literal['user_leave']
    clientId: str
    carId: str


class CollisionKind(Enum):
    vehicle_vehicle = 'vehicle_vehicle'
    vehicle_pedestrian = 'vehicle_pedestrian'


class Payload2(BaseModel):
    kind: Literal['collision']
    entities: list[str] = Field(..., max_length=2, min_length=2)
    collisionKind: CollisionKind


class Payload3(BaseModel):
    kind: Literal['ev_spawn']
    evId: str
    route: list[str]


class Payload4(BaseModel):
    kind: Literal['ev_preempt']
    intersectionId: str
    etaS: float


class Payload5(BaseModel):
    kind: Literal['ev_complete']
    evId: str
    transitTimeS: float


class Model(BaseModel):
    type: Literal['room_event']
    ts: float
    payload: Payload | Payload1 | Payload2 | Payload3 | Payload4 | Payload5
