# generated by datamodel-codegen:
#   filename:  scenario-control.schema.json

from __future__ import annotations

from enum import Enum
from typing import Literal

from pydantic import BaseModel


class Model(BaseModel):
    pass


class Scenario(Enum):
    rush_hour = 'rush_hour'
    emergency_vehicle = 'emergency_vehicle'
    chaos = 'chaos'
    pedestrian_pressure = 'pedestrian_pressure'


class Payload(BaseModel):
    scenario: Scenario


class StartScenarioMessage(BaseModel):
    type: Literal['start_scenario']
    ts: float
    payload: Payload


class Result(Enum):
    pass_ = 'pass'
    fail = 'fail'


class Payload1(BaseModel):
    scenario: str
    result: Result
    avgWaitDeltaPct: float


class ScenarioCompleteMessage(BaseModel):
    type: Literal['scenario_complete']
    ts: float
    payload: Payload1
